services:
  - type: static
    name: frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublicPath: ./frontend/dist
    routes:
      - path: /*
        destination: /index.html
        statusCode: 200